### ISSUE TITLE
missing texture??

### ISSUE THREAD

**Issue by poly-1810** [the-realest-stu/DynamicTrees-BOP#100]
![image](https://github.com/DynamicTreesTeam/DynamicTrees-BOP/assets/105131270/eb00eb25-10ea-4ad9-aaf9-cc62d3d6c4be)
kinda self explanatory, redwood sapling doesnt have tex when placed via cone

**Comment by KillerCoati** [comment]
I'm also having this issue - 1.19.2 (forge 43.2.8), Dynamic Trees BOP v 3.1.1

**Comment by Nycto97** [comment]
![2023-09-26_08 53 16](https://github.com/DynamicTreesTeam/DynamicTrees-BOP/assets/83367226/2e6b86b4-d72d-4427-bba5-33efe73d4c8b)
Was about to make an issue for this :) Forge 1.19.2 43.2.23 | DynamicTreesBOP-1.19.2-3.1.1

**Comment by JamZia** [comment]
Can confirm that this is happening for all versions of the mod.

**Comment by supermassimo** [comment]
should be fixed in [1.18.2-3.0.2](https://legacy.curseforge.com/minecraft/mc-mods/dtbop/files/4808598) and [1.19.2-3.1.2](https://legacy.curseforge.com/minecraft/mc-mods/dtbop/files/4808632)
