### ISSUE TITLE
1.20.1 glowing grotto still generates non-dynamic giant glowshrooms but manually growing them from glowshroom cap works

### ISSUE THREAD

**Issue by zuel122** [the-realest-stu/DynamicTrees-BOP#119]
I'm not sure if this is intentional (if it's really hard to generate dynamic trees underground or something) as I can't find mention that they shouldn't be, but the giant glowshrooms in the glowing grotto underground biome are still generating in non-dynamic form. "Dynamic Trees +" and "Dynamic Trees - Biomes O' Plenty" do seem to be working together with dynamic toadstools growing in fungal jungle and manually glowing dynamic glowshrooms from cap also working.

Tested with almost the bare minimum mods to get dynamic BOP to grow with the only extra thing being nature's compass just to let me find them quickly.

Love the mushrooms finally being dynamic though <3

**Comment by supermassimo** [comment]
Underground biomes are not yet supported in dynamic trees, we are working on it <3

**Comment by supermassimo** [comment]
Done
