### ISSUE TITLE
Crash on world gen 1.20.1 with Dynamic Trees+ installed

### ISSUE THREAD

**Issue by IceCubeDragon** [the-realest-stu/DynamicTrees-BOP#124]
There seems to be an issue when dynamic trees BOP is installed with Dynamic Trees+ involving mushrooms- it's been tested in isolation and the error still comes up even with only the mods needed to run the combo installed

https://mclo.gs/nx0eTNp

**Comment by dyrkuwu** [comment]
same, seems like one of the mods were updated

**Comment by supermassimo** [comment]
BOP has updated and now an update is needed on our side. Please downgrade Biomes o' Plenty to version 18 until this is fixed

**Comment by supermassimo** [comment]
Fixed in [3.3.1](https://www.curseforge.com/minecraft/mc-mods/dtbop/files/5939807)
