### ISSUE TITLE
[1.20.1] New maple wood type update incompatibility 

### ISSUE THREAD

**Issue by Lyxairo** [the-realest-stu/DynamicTrees-BOP#127]
Please update the mod to include the new maple log type and Empyrean sappling in BoP's 1.20.1-12.0.0.91 

Maple samaras grow maple trees, but the trunks are made out of oak instead
![2024-11-17_20 00 29](https://github.com/user-attachments/assets/5c910cf5-598d-4060-9144-15a88cae9409)

**Comment by Groupix05** [comment]
Empyrean is a new tree that generates in the end, but in 1.20.1, there is no end biomes, so this tree is not urgent.

**Comment by supermassimo** [comment]
Fixed on [3.3.1](https://www.curseforge.com/minecraft/mc-mods/dtbop/files/5939807)
Please make a new issue about the empyrean tree
