### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by BenRohel** [the-realest-stu/DynamicTrees-BOP#15]
I made the french language file, but as minecraft says "*translation may not be 100% accurate*", because I'm french and there are a lot of complex terms relative to tree seeds.

I can't send directly the lang file, so here is its content. I hope you could add it to the next version of your mod.
I encourage other people suggesting translation for other languages.

PS: I didn't find what are *Hellish* and *Hellbark*, so I let them in english.

item.yellowautumnseed.name=Chaton de Bouleau automnal
item.orangeautumnseed.name=Gland de Chêne automnal
item.magicseed.name=Cypsela Magique
item.umbranseed.name=Graine d'Arbre Parapluie
item.umbranconiferseed.name=Pomme d'Arbre Parapluie
item.oakdyingseed.name=Gland de Chêne Mourant
item.firseed.name=Pomme de Sapin
item.pinkcherryseed.name=Graine de Cerisier Rose
item.whitecherryseed.name=Graine de Cerisier Blanc
item.mapleseed.name=Samare d'Érable
item.hellbarkseed.name=Hellish Acorn
item.jacarandaseed.name=Cosse de Jacaranda
item.mangroveseed.name=Plant de Palétuvier
item.redwoodseed.name=Pomme de Séquoia
item.willowseed.name=Chaton de Saule
item.pineseed.name=Pomme de Pin
item.mahoganyseed.name=Pousse d'Acajou
item.ebonyseed.name=Cosse d'Ébène
item.eucalyptusseed.name=Capsule d'Eucalyptus
item.bambooseed.name=Pousse de Bambou

item.floweringoakseed.name=Gland de Chêne Fleuri
item.palmseed.name=Graine de Palmier

tile.leaves0.name=Feuilles Dynamiques
tile.leaves1.name=Feuilles Dynamiques
tile.leaves2.name=Feuilles Dynamiques
tile.leaves3.name=Feuilles Dynamiques
tile.leaves4.name=Feuilles Dynamiques
tile.leaves5.name=Feuilles Dynamiques
tile.leaves6.name=Feuilles Dynamiques
tile.leaves7.name=Feuilles Dynamiques

tile.leaves_flowering.name=Feuilles Dynamiques
tile.leaves_palm.name=Feuilles Dynamiques

tile.dynamictreesbop:magicbranch.name=Arbre Magique Dynamique
tile.dynamictreesbop:umbranbranch.name=Arbre Parapluie Dynamique
tile.dynamictreesbop:umbranconiferbranch.name=Arbre Parapluie Dynamique
tile.dynamictreesbop:firbranch.name=Sapin Dynamique
tile.dynamictreesbop:cherrybranch.name=Cerisier Dynamique
tile.dynamictreesbop:hellbarkbranch.name=Dynamic Hellbark Tree
tile.dynamictreesbop:deadbranch.name=Arbre Mort Dynamique
tile.dynamictreesbop:jacarandabranch.name=Jacaranda Dynamique
tile.dynamictreesbop:mangrovebranch.name=Palétuvier Dynamique
tile.dynamictreesbop:redwoodbranch.name=Séquoia Dynamique
tile.dynamictreesbop:willowbranch.name=Saule Dynamique
tile.dynamictreesbop:pinebranch.name=Pin Dynamique
tile.dynamictreesbop:mahoganybranch.name=Acajou Dynamique
tile.dynamictreesbop:ebonybranch.name=Ébène Dynamique
tile.dynamictreesbop:eucalyptusbranch.name=Eucalyptus Dynamique
tile.dynamictreesbop:bamboobranch.name=Bambou Dynamique

tile.dynamictreesbop:decayedbranch.name=Arbre Mort Dynamique
tile.dynamictreesbop:palmbranch.name=Palmier Dynamique

**Comment by SkyHawkB** [comment]
I think you should make a PR. If you don't know how, I can make one for you.
