### ISSUE TITLE
Dead trees do not drop items

### ISSUE THREAD

**Issue by Ash70** [the-realest-stu/DynamicTrees-BOP#21]
BOP 7.0.1.2399
DynamicTrees BOP 1.2
Forge 2760

Chopping down a dead tree does not drop any logs or sticks.

EDIT: And I just noticed that breaking a branch, breaks the whole tree.

**Comment by ferreusveritas** [comment]
I fixed the branch breaking taking down the whole tree problem.

**Comment by the-realest-stu** [comment]
Fixed in version 0.3.2
