### ISSUE TITLE
Crash with flower_vine (latest build dynamictress BOP and fresh server)

### ISSUE THREAD

**Issue by Dhannyjsb** [the-realest-stu/DynamicTrees-BOP#27]
This crash report and latest log for flower vine error
Crash Report : https://paste.dimdev.org/uguvihemep.rb
Latest Log : https://paste.dimdev.org/mejajevohu.md

**Comment by Malrama** [comment]
I can confirm this :)

Greetings

**Comment by ferreusveritas** [comment]
Fixed
