### ISSUE TITLE
1.12.2 Twitch platform crash

### ISSUE THREAD

**Issue by DraconicKid** [the-realest-stu/DynamicTrees-BOP#30]
Crash in Pastebin, located [here ](https://pastebin.com/GFsrLEh6)

Crash complains of an error line 51,

> dynamictreesbop.trees.species.SpeciesOakFloweringVine.<init>(SpeciesOakFloweringVine.java:51)

BoP is installed, so I'm at a loss and had to report it

**Comment by ferreusveritas** [comment]
Upgrade DynamicTrees-BOP to latest alpha from curseforge.
