### ISSUE TITLE
Crash client

### ISSUE THREAD

**Issue by SeagalKru** [the-realest-stu/DynamicTrees-BOP#38]
[crash-2019-01-20_15.21.57-client.txt](https://github.com/the-realest-stu/DynamicTrees-BOP/files/2776574/crash-2019-01-20_15.21.57-client.txt)
[latest.log](https://github.com/the-realest-stu/DynamicTrees-BOP/files/2776575/latest.log)

**Comment by ferreusveritas** [comment]
DynamicTreesBOP-1.12.2-1.3.2.jar -> DynamicTreesBOP-1.12.2-1.4.1e.jar

**Comment by SeagalKru** [comment]
Made! Thank you!
