### ISSUE TITLE
Server crashs with DynamicTreesBOP-1.16.5-2.0.2.jar

### ISSUE THREAD

**Issue by agentwolf88** [the-realest-stu/DynamicTrees-BOP#63]
[crash-2021-06-24_11.13.46-fml.txt](https://github.com/the-realest-stu/DynamicTrees-BOP/files/6708013/crash-2021-06-24_11.13.46-fml.txt)

**Comment by ItzDNP** [comment]
Got the same problem, any fix?

**Comment by supermassimo** [comment]
fixed in [2.0.3](https://www.curseforge.com/minecraft/mc-mods/dtbop/files/3363402)
