### ISSUE TITLE
Dynamic trees now having load errors after installing this mod

### ISSUE THREAD

**Issue by imperialR3D** [the-realest-stu/DynamicTrees-BOP#66]
I had both dynamic trees and Biomes O' Plenty installed in a modpack for a while before I found this mod. I wanted my worlds to be more consistent so I downloaded this mod. However, on startup, I now get a load error that states "Dynamic trees (dynamic trees) encountered an error during the create_Registries even phase" I tried downloading earlier versions of the mod to no avail. I also tried using just this mod and its parent mods to see if it was a compatibility issue with one of the other mods in my modpack, this also didn't work. How do I get this mod to work?

**Comment by supermassimo** [comment]
Please include the log, without it I cannot do anything.
Make sure you are on the latest version for both DT and DT-BoP too

**Comment by imperialR3D** [comment]
ah sorry, forgot about the log, I've attached my latest.log here:
[latest.log](https://github.com/the-realest-stu/DynamicTrees-BOP/files/6727265/latest.log) 

also, I've copy-pasted the contents of the crash report from the load error into this document: 
[(minecraft dynamic trees crash report) crash-2021-06-28_10.51.09-fml.txt](https://github.com/the-realest-stu/DynamicTrees-BOP/files/6727292/minecraft.dynamic.trees.crash.report.crash-2021-06-28_10.51.09-fml.txt)

I hope this helps to resolve the issue.

**Comment by imperialR3D** [comment]
ah... I didn't realize there was a new version of Dynamic trees available. everything seems to be working now that I have it downloaded.
