### ISSUE TITLE
Bop crash in 1.16.5

### ISSUE THREAD

**Issue by Brodley237** [the-realest-stu/DynamicTrees-BOP#71]
whenever i combine DynamicTrees-1.16.5-0.10.0-Beta24 with DynamicTreesBOP-1.16.5-2.0.6 and BiomesOPlenty-1.16.5-13.1.0.477-universal, i run a bop world, but the dynamic trees dont show up for the bop trees, and when i try to go to the config in the mod options for dynamic trees bop, the game instantly crashes the second i click the mod

**Comment by supermassimo** [comment]
duplicate of https://github.com/DynamicTreesTeam/DynamicTrees-BOP/issues/69
