### ISSUE TITLE
Cherry sapling/pit recipes possibly mixed up

### ISSUE THREAD

**Issue by Maltshakes** [the-realest-stu/DynamicTrees-BOP#72]
Crafting a Pink Cherry Pit together with a Dirt Bucket gives a White Cherry Sapling instead of a Pink Cherry Sapling. Also, according to JEI, two recipes are listed for crafting a White Cherry Sapling together with a Dirt Bucket. One recipe says it gives the expected White Cherry Pit while the second says it gives a Pink Cherry Pit.

**Comment by supermassimo** [comment]
Has been fixed
