### ISSUE TITLE
[1.18.2] No trees generating in Mediterranean Forest biome

### ISSUE THREAD

**Issue by Maltshakes** [the-realest-stu/DynamicTrees-BOP#91]
Mod version 3.0.0

As the title says, there are no dynamic trees, nor any trees at all, generating in BOP's Mediterranean Forest biome

![image](https://user-images.githubusercontent.com/76584081/211075127-fafeec60-4e20-4aaf-8d2a-18eca4d016f6.png)

**Comment by Nyfaria** [comment]
fixed in recent push, update to be published soon.
