### ISSUE TITLE
Error whilst loading type "Family" with name "dtbop:burnt": [common_leaves] Could not find LeavesProperties for registry name 'dtbop:burnt'.

### ISSUE THREAD

**Issue by xFirefalconx** [the-realest-stu/DynamicTrees-BOP#92]
Console: **Error whilst loading type "Family" with name "dtbop:burnt": [common_leaves] Could not find LeavesProperties for registry name 'dtbop:burnt'.**

I'm currently running a debug session with my WIP 190 mods modpack. There is an error showing up in the console directed at this mod. There could be a compatibility error though as before I encountered a cross mod issue that concerned 4 mods of my pack, which was potentially caused by wrong item registration (just a side info, the mod is AsticorCarts and currently has to be fixed, check if it isn't related to this). 

Can you check if you can find any loophole in the mentioned code section?

My latest.Log (I currently cannot join a world because of a package issue, omw to resolve that.)
[latest.log](https://github.com/DynamicTreesTeam/DynamicTrees-BOP/files/10734316/latest.log)

**Comment by xFirefalconx** [comment]
Minecraft version 1.18.2
Forge 40.2.0

**Comment by CSdiscoveries** [comment]
I am having the same issue, but on 1.16.5. Game loadup hangs for 20 minutes, and then this is the nest thing in the log. In game, there's a different possibly related issue; BOP trees don't drop anything if I cut them down. They're dynamic, though.

**Comment by CSdiscoveries** [comment]
I've managed to confirm that this is an issue when only BOP, this mod, and Dynamic Trees are installed on 1.16.5, Forge 36.2.34. It doesn't cause the loading to hang for as long, at least. However, it's still an issue... And, it's not limited to this mod either. Other "Compatibility Mods" for Dynamic trees throw the same error, only in reference to their own items instead. Considering how much of an issue this is... it needs to be fixed, or I might have to just remove it from my pack along with all the other DT-related mods...
