### ISSUE TITLE
[1.18.2] Crash: Exception Ticking World

### ISSUE THREAD

**Issue by DeshiDesu** [the-realest-stu/DynamicTrees-BOP#95]
I do not know what happened but I do have a crash report:

>[crash-2023-04-08_20.46.33-server.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/11184561/crash-2023-04-08_20.46.33-server.txt)

**Mod version:**
 >DynamicTrees-1.18.2-0.11.0-Beta9
 >DynamicTreesBOP-1.18.2-3.0.0-Beta3

**Modloader:**
 >Forge 40.2.1

**Comment by APrimevalWorld** [comment]
I have the exact same problem with a very similar looking error report. I'm going to test with an earlier version of DT to see if it fixes the problem.

https://pastebin.com/qQnVA1Xm

**Comment by DeshiDesu** [comment]
I'm glad I am not the only one facing this problem. It seems the issue is caused by:
java.lang.NoSuchMethodError: 'boolean com.ferreusveritas.dynamictrees.block.rooty.SoilHelper.isSoilAcceptable(net.minecraft.world.level.block.state.BlockState, int, boolean)'

**Comment by Groupix05** [comment]
Same error here , I have a lot of mods but its very similar :

[crash-2023-04-23_23.31.51-server.txt](https://github.com/DynamicTreesTeam/DynamicTrees-BOP/files/11305014/crash-2023-04-23_23.31.51-server.txt)

Its on Forge 40.2.2 .

**Comment by supermassimo** [comment]
Please try this patch and let me know if you are still having the issue https://legacy.curseforge.com/minecraft/mc-mods/dtbop/files/4535955

**Comment by Groupix05** [comment]
The probleme was fixed with the beta 4
Thanks !

If you want to try just go in a Bayou biome ,the game crash instantly in beta3 .

**Comment by supermassimo** [comment]
Fixed in 3.0.0-Beta4
