### ISSUE TITLE
[1.18.2] Crash When Breaking Any BOP Tree in Survival

### ISSUE THREAD

**Issue by ChrisClickbait** [the-realest-stu/DynamicTrees-BOP#97]
Game Version -- 1.18.2
Forge -- 40.1.84
BOP -- 1.18.2-16.0.0.134
TerraBlender -- 1.2.0.126
DT -- 1.18.2-1.02
DTBOP -- 1.18.2-3.00.0-Beta4
DT+ -- 1.18.2-1.0.0

Pretty much getting this crash when breaking a tree in survival with an axe. 
https://pastebin.com/Q2TwgjDK
Let me know if you need anymore info.

**Comment by supermassimo** [comment]
Please try this patch and let me know if you are still having the issue https://legacy.curseforge.com/minecraft/mc-mods/dtbop/files/4535955

**Comment by ChrisClickbait** [comment]
Nope, still crashing. 

https://pastebin.com/egtnwEPe

**Comment by Harleyoc1** [comment]
Can't reproduce in the latest version. Please reply again if you still encounter this issue.
